name: iOS Build


on:
  push:
    branches: [ main, cmp_ios_desktop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    env:
      XCODE_VERSION: '26.1'

    steps:
      - uses: actions/checkout@v4


      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_26.1.app

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build shared framework
        run: ./gradlew :shared:linkDebugFrameworkIosSimulatorArm64

      - name: List Xcode versions
        run: ls /Applications/ | grep Xcode

      - name: Build iOS app
        run: |
          xcodebuild build \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            IPHONEOS_DEPLOYMENT_TARGET=18.5